services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rpa_net

  backend:
    build:
      context: ../backend
    container_name: backend
    restart: on-failure
    env_file:
      - .env
    environment:
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      PYTHONUNBUFFERED: 1
      DEBUG: "True"
      DOCKER_ENV: 1
    volumes:
      - ../backend/app:/app
    expose:
      - "8000"
      - "5678"
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - mysql
    command: ["python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - rpa_net

  frontend:
    image: php:8.2-apache
    container_name: frontend
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ../frontend:/var/www/html
    depends_on:
      - mysql
    networks:
      - rpa_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend:/var/www/html
    depends_on:
      - backend
      - frontend
    networks:
      - rpa_net

volumes:
  mysql_data:

networks:
  rpa_net:
    driver: bridge